package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

func (g *generator) renderContracts() ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/gentypes; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Frozen input digest: %s\n", inputDigest(g.inputs))
	fmt.Fprintln(&out, "package platformcontract")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, `import "fmt"`)
	fmt.Fprintln(&out)

	sort.Slice(g.enums, func(i, j int) bool { return g.enums[i].name < g.enums[j].name })
	for _, enum := range g.enums {
		emitEnum(&out, enum)
	}

	models := append([]*typeModel(nil), g.models...)
	sort.Slice(models, func(i, j int) bool { return models[i].name < models[j].name })
	for _, model := range models {
		if model.category == "manual" {
			continue
		}
		if err := emitTypeModel(&out, model); err != nil {
			return nil, err
		}
	}

	contracts := g.contractSchemas()
	fmt.Fprintf(&out, "const GeneratedSchemaTypeCount = %d\n", len(contracts))
	fmt.Fprintf(&out, "const GeneratedPrimaryEnumCount = %d\n", g.primaryEnumCount())
	fmt.Fprintln(&out)
	emitContractDispatch(&out, contracts)

	dispositions, err := g.fieldDispositions()
	if err != nil {
		return nil, err
	}
	if len(dispositions) != 439 {
		return nil, fmt.Errorf("gentypes: generated property dispositions=%d, want 439", len(dispositions))
	}
	transportCount := 0
	for _, disposition := range dispositions {
		if strings.HasPrefix(disposition, "transport-only:") {
			transportCount++
		}
	}
	if transportCount != 1 {
		return nil, fmt.Errorf("gentypes: transport-only dispositions=%d, want 1", transportCount)
	}
	fmt.Fprintf(&out, "const GeneratedSchemaPropertyCount = %d\n", len(dispositions))
	fmt.Fprintf(&out, "const GeneratedFieldDispositionSHA256 = %q\n", fieldDispositionDigest(dispositions))
	fmt.Fprintln(&out, "var generatedFieldDispositions = map[string]string{")
	for _, pointer := range sortedStringKeys(dispositions) {
		fmt.Fprintf(&out, "\t%q: %q,\n", pointer, dispositions[pointer])
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "// generatedFieldAccessors makes every field disposition a compile-time")
	fmt.Fprintln(&out, "// checked method expression. Union and transport-only dispositions are")
	fmt.Fprintln(&out, "// deliberately represented only by their explicit disposition tags.")
	fmt.Fprintln(&out, "var generatedFieldAccessors = map[string]any{")
	for _, pointer := range sortedStringKeys(dispositions) {
		disposition := dispositions[pointer]
		target, ok := strings.CutPrefix(disposition, "field:")
		if !ok {
			continue
		}
		separator := strings.LastIndex(target, ".")
		if separator <= 0 || separator == len(target)-1 {
			return nil, fmt.Errorf("gentypes: malformed field disposition %q for %s", disposition, pointer)
		}
		fmt.Fprintf(&out, "\t%q: %s.%s,\n", pointer, target[:separator], target[separator+1:])
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "func GeneratedFieldDispositions() map[string]string {")
	fmt.Fprintln(&out, "\tresult := make(map[string]string, len(generatedFieldDispositions))")
	fmt.Fprintln(&out, "\tfor pointer, disposition := range generatedFieldDispositions {")
	fmt.Fprintln(&out, "\t\tresult[pointer] = disposition")
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "\treturn result")
	fmt.Fprintln(&out, "}")
	return out.Bytes(), nil
}

func fieldDispositionDigest(dispositions map[string]string) string {
	var canonical bytes.Buffer
	canonical.WriteByte('{')
	for index, pointer := range sortedStringKeys(dispositions) {
		if index > 0 {
			canonical.WriteByte(',')
		}
		canonical.WriteString(strconv.Quote(pointer))
		canonical.WriteByte(':')
		canonical.WriteString(strconv.Quote(dispositions[pointer]))
	}
	canonical.WriteByte('}')
	return fmt.Sprintf("%x", sha256.Sum256(canonical.Bytes()))
}

func emitEnum(out *bytes.Buffer, enum *enumModel) {
	fmt.Fprintf(out, "type %s string\n\n", enum.name)
	fmt.Fprintln(out, "const (")
	used := map[string]bool{}
	for _, value := range enum.values {
		name := enum.name + exportedIdentifier(value)
		if used[name] {
			name += shortHash(value)
		}
		used[name] = true
		fmt.Fprintf(out, "\t%s %s = %q\n", name, enum.name, value)
	}
	fmt.Fprintln(out, ")")
	fmt.Fprintf(out, "func (value %s) Valid() bool {\n", enum.name)
	fmt.Fprintln(out, "\tswitch value {")
	fmt.Fprint(out, "\tcase ")
	for index, value := range enum.values {
		if index > 0 {
			fmt.Fprint(out, ", ")
		}
		fmt.Fprintf(out, "%s(%q)", enum.name, value)
	}
	fmt.Fprintln(out, ":")
	fmt.Fprintln(out, "\t\treturn true")
	fmt.Fprintln(out, "\tdefault:")
	fmt.Fprintln(out, "\t\treturn false")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "}")
	fmt.Fprintf(out, "func build%s(_ *Validator, raw any) (%s, error) {\n", enum.name, enum.name)
	fmt.Fprintln(out, "\tvalue, err := requireString(raw, \"generated enum\")")
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s(\"\"), err\n", enum.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\tresult := %s(value)\n", enum.name)
	fmt.Fprintln(out, "\tif !result.Valid() {")
	fmt.Fprintf(out, "\t\treturn %s(\"\"), fmt.Errorf(\"platformcontract: generated enum %s rejected %%q\", value)\n", enum.name, enum.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn result, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitTypeModel(out *bytes.Buffer, model *typeModel) error {
	switch model.category {
	case "scalar":
		emitScalarModel(out, model)
	case "enum":
		emitEnumContractModel(out, model)
	case "array":
		emitArrayModel(out, model)
	case "object":
		emitObjectModel(out, model)
	case "union":
		emitUnionModel(out, model)
	default:
		return fmt.Errorf("gentypes: cannot emit %s category %q", model.name, model.category)
	}
	return nil
}

func emitContractMethods(out *bytes.Buffer, model *typeModel) {
	if !model.contract {
		return
	}
	fmt.Fprintf(out, "func (%s) SchemaName() string { return %q }\n", model.name, schemaPublicName(model))
	fmt.Fprintf(out, "func (%s) sealedTypedContract() {}\n", model.name)
}

func schemaPublicName(model *typeModel) string {
	if model.ref.pointer == "#" {
		return model.name
	}
	parts := strings.Split(model.ref.pointer, "/")
	return unescapePointer(parts[len(parts)-1])
}

func emitScalarModel(out *bytes.Buffer, model *typeModel) {
	fmt.Fprintf(out, "type %s struct { value string }\n", model.name)
	emitContractMethods(out, model)
	fmt.Fprintf(out, "func (value %s) String() string { return value.value }\n", model.name)
	fmt.Fprintf(out, "func (value %s) Value() string { return value.value }\n", model.name)
	fmt.Fprintf(out, "func build%s(_ *Validator, raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tvalue, err := requireString(raw, %q)\n", model.name)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\treturn %s{value: value}, nil\n", model.name)
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitEnumContractModel(out *bytes.Buffer, model *typeModel) {
	fmt.Fprintf(out, "type %s struct { value %s }\n", model.name, model.enum.name)
	emitContractMethods(out, model)
	fmt.Fprintf(out, "func (value %s) Value() %s { return value.value }\n", model.name, model.enum.name)
	fmt.Fprintf(out, "func build%s(v *Validator, raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tvalue, err := build%s(v, raw)\n", model.enum.name)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\treturn %s{value: value}, nil\n", model.name)
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitArrayModel(out *bytes.Buffer, model *typeModel) {
	fmt.Fprintf(out, "type %s struct { values []%s }\n", model.name, model.arrayElement.goType)
	emitContractMethods(out, model)
	fmt.Fprintf(out, "func (value %s) Values() []%s {\n", model.name, model.arrayElement.goType)
	fmt.Fprintf(out, "\treturn append([]%s(nil), value.values...)\n", model.arrayElement.goType)
	fmt.Fprintln(out, "}")
	fmt.Fprintf(out, "func build%s(v *Validator, raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tvalues, err := buildGeneratedSlice(v, raw, %q, %s)\n", model.name, model.arrayElement.builder)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\treturn %s{values: values}, nil\n", model.name)
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitObjectModel(out *bytes.Buffer, model *typeModel) {
	for _, union := range model.embeddedUnions {
		fmt.Fprintf(out, "type %s uint8\n", union.name)
		fmt.Fprintln(out, "const (")
		fmt.Fprintf(out, "\t%sInvalid %s = iota\n", union.name, union.name)
		for index := 0; index < union.branches; index++ {
			fmt.Fprintf(out, "\t%sVariant%d\n", union.name, index+1)
		}
		fmt.Fprintln(out, ")")
	}
	fmt.Fprintf(out, "type %s struct {\n", model.name)
	for _, field := range model.fields {
		fieldType := field.spec.goType
		if !field.required {
			fieldType = "optionalValue[" + fieldType + "]"
		}
		fmt.Fprintf(out, "\t%s %s\n", field.private, fieldType)
	}
	if model.open {
		fmt.Fprintln(out, "\tadditional JsonObject")
	}
	for _, union := range model.embeddedUnions {
		fmt.Fprintf(out, "\t%s %s\n", union.privateName, union.name)
	}
	fmt.Fprintln(out, "}")
	emitContractMethods(out, model)
	for _, field := range model.fields {
		if field.writeOnly {
			continue
		}
		if field.required {
			fmt.Fprintf(out, "func (value %s) %s() %s {\n", model.name, field.goName, field.spec.goType)
			if field.spec.slice {
				fmt.Fprintf(out, "\treturn append([]%s(nil), value.%s...)\n", field.spec.element.goType, field.private)
			} else {
				fmt.Fprintf(out, "\treturn value.%s\n", field.private)
			}
			fmt.Fprintln(out, "}")
		} else {
			fmt.Fprintf(out, "func (value %s) %s() (%s, bool) {\n", model.name, field.goName, field.spec.goType)
			fmt.Fprintf(out, "\tif !value.%s.set {\n", field.private)
			fmt.Fprintf(out, "\t\tvar zero %s\n", field.spec.goType)
			fmt.Fprintln(out, "\t\treturn zero, false")
			fmt.Fprintln(out, "\t}")
			if field.spec.slice {
				fmt.Fprintf(out, "\treturn append([]%s(nil), value.%s.value...), true\n", field.spec.element.goType, field.private)
			} else {
				fmt.Fprintf(out, "\treturn value.%s.value, true\n", field.private)
			}
			fmt.Fprintln(out, "}")
		}
	}
	if model.open {
		fmt.Fprintf(out, "func (value %s) Additional() JsonObject { return value.additional }\n", model.name)
	}
	for _, union := range model.embeddedUnions {
		fmt.Fprintf(out, "func (value %s) %s() %s { return value.%s }\n", model.name, union.name, union.name, union.privateName)
	}
	if model.name == "WebSocketReauth" {
		fmt.Fprintln(out, "func (WebSocketReauth) MarshalJSON() ([]byte, error) {")
		fmt.Fprintln(out, "\treturn nil, fmt.Errorf(\"platformcontract: WebSocketReauth is transport-only and cannot be marshaled\")")
		fmt.Fprintln(out, "}")
		fmt.Fprintln(out, "func (WebSocketReauth) MarshalText() ([]byte, error) {")
		fmt.Fprintln(out, "\treturn nil, fmt.Errorf(\"platformcontract: WebSocketReauth is transport-only and cannot be marshaled\")")
		fmt.Fprintln(out, "}")
		fmt.Fprintln(out, "func (WebSocketReauth) Format(state fmt.State, _ rune) {")
		fmt.Fprintln(out, "\t_, _ = fmt.Fprint(state, \"WebSocketReauth{access_token_transport:[REDACTED]}\")")
		fmt.Fprintln(out, "}")
	}
	fmt.Fprintf(out, "func build%s(v *Validator, raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tobject, err := requireObject(raw, %q)\n", model.name)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\t_ = object")
	fmt.Fprintf(out, "\tvar result %s\n", model.name)
	for _, field := range model.fields {
		if field.required {
			emitValueBuild(out, field.spec, "object["+strconv.Quote(field.jsonName)+"]", "converted"+field.goName, "\t")
			fmt.Fprintf(out, "\tresult.%s = converted%s\n", field.private, field.goName)
		} else {
			fmt.Fprintf(out, "\tif fieldValue, exists := object[%q]; exists {\n", field.jsonName)
			emitValueBuild(out, field.spec, "fieldValue", "converted"+field.goName, "\t\t")
			fmt.Fprintf(out, "\t\tresult.%s = presentValue(converted%s)\n", field.private, field.goName)
			fmt.Fprintln(out, "\t}")
		}
	}
	if model.open {
		fmt.Fprintln(out, "\tknownFields := map[string]bool{")
		for _, field := range model.fields {
			fmt.Fprintf(out, "\t\t%q: true,\n", field.jsonName)
		}
		fmt.Fprintln(out, "\t}")
		fmt.Fprintln(out, "\tresult.additional, err = additionalJsonObject(object, knownFields)")
		fmt.Fprintln(out, "\tif err != nil {")
		fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
		fmt.Fprintln(out, "\t}")
	}
	for _, union := range model.embeddedUnions {
		fmt.Fprintf(out, "\tbranch%s, err := generatedUnionBranch(v, %q, %q, %q, raw)\n", union.name, model.ref.doc.key, union.pointer, union.keyword)
		fmt.Fprintln(out, "\tif err != nil {")
		fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
		fmt.Fprintln(out, "\t}")
		fmt.Fprintf(out, "\tresult.%s = %s(branch%s + 1)\n", union.privateName, union.name, union.name)
	}
	fmt.Fprintln(out, "\treturn result, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitValueBuild(out *bytes.Buffer, spec *valueSpec, source, variable, indent string) {
	if spec.slice {
		fmt.Fprintf(out, "%s%s, err := buildGeneratedSlice(v, %s, %q, %s)\n", indent, variable, source, variable, spec.element.builder)
	} else {
		fmt.Fprintf(out, "%s%s, err := %s(v, %s)\n", indent, variable, spec.builder, source)
	}
	fmt.Fprintf(out, "%sif err != nil {\n", indent)
	fmt.Fprintf(out, "%s\treturn result, err\n", indent)
	fmt.Fprintf(out, "%s}\n", indent)
}

func emitUnionModel(out *bytes.Buffer, model *typeModel) {
	kindName := model.name + "Kind"
	fmt.Fprintf(out, "type %s uint8\n", kindName)
	fmt.Fprintln(out, "const (")
	fmt.Fprintf(out, "\t%sInvalid %s = iota\n", kindName, kindName)
	for _, branch := range model.unionBranches {
		fmt.Fprintf(out, "\t%s%s\n", kindName, branch.name)
	}
	fmt.Fprintln(out, ")")
	fmt.Fprintf(out, "type %s struct {\n", model.name)
	fmt.Fprintf(out, "\tkind %s\n", kindName)
	for _, branch := range model.unionBranches {
		fmt.Fprintf(out, "\t%s optionalValue[%s]\n", branch.private, branch.spec.goType)
	}
	fmt.Fprintln(out, "}")
	emitContractMethods(out, model)
	fmt.Fprintf(out, "func (value %s) Kind() %s { return value.kind }\n", model.name, kindName)
	for _, branch := range model.unionBranches {
		fmt.Fprintf(out, "func (value %s) %s() (%s, bool) {\n", model.name, branch.name, branch.spec.goType)
		fmt.Fprintf(out, "\tif !value.%s.set {\n", branch.private)
		fmt.Fprintf(out, "\t\tvar zero %s\n", branch.spec.goType)
		fmt.Fprintln(out, "\t\treturn zero, false")
		fmt.Fprintln(out, "\t}")
		fmt.Fprintf(out, "\treturn value.%s.value, true\n", branch.private)
		fmt.Fprintln(out, "}")
	}
	fmt.Fprintf(out, "func build%s(v *Validator, raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tbranch, err := generatedUnionBranch(v, %q, %q, %q, raw)\n", model.ref.doc.key, model.unionPointer, model.unionKeyword)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\tvar result %s\n", model.name)
	fmt.Fprintf(out, "\tresult.kind = %s(branch + 1)\n", kindName)
	fmt.Fprintln(out, "\tswitch branch {")
	for index, branch := range model.unionBranches {
		fmt.Fprintf(out, "\tcase %d:\n", index)
		emitValueBuild(out, branch.spec, "raw", "converted", "\t\t")
		fmt.Fprintf(out, "\t\tresult.%s = presentValue(converted)\n", branch.private)
	}
	fmt.Fprintln(out, "\tdefault:")
	fmt.Fprintf(out, "\t\treturn %s{}, fmt.Errorf(\"platformcontract: generated union branch %%d is invalid\", branch)\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn result, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

type contractSchema struct {
	name    string
	model   *typeModel
	manual  string
	builder string
}

func (g *generator) contractSchemas() []contractSchema {
	var result []contractSchema
	for _, doc := range g.documents {
		if doc.platformDefs {
			for _, name := range sortedMapKeys(doc.defs) {
				refKey := doc.key + "#/$defs/" + escapePointer(name)
				if isManualSchemaName(name) {
					builder := map[string]string{
						"JsonObject":          "buildJsonObjectField",
						"JsonValue":           "buildJsonValueField",
						"UntrustedJsonObject": "buildUntrustedJsonObjectField",
						"UntrustedJsonValue":  "buildUntrustedJsonValueField",
					}[name]
					result = append(result, contractSchema{name: name, manual: name, builder: builder})
				} else {
					model := g.modelsByRef[refKey]
					result = append(result, contractSchema{name: name, model: model, builder: "build" + model.name})
				}
			}
		} else {
			model := g.modelsByRef[doc.key+"#"]
			result = append(result, contractSchema{name: doc.rootName, model: model, builder: "build" + model.name})
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].name < result[j].name })
	return result
}

func emitContractDispatch(out *bytes.Buffer, contracts []contractSchema) {
	fmt.Fprintln(out, "func buildGeneratedContract(v *Validator, name string, raw any) (TypedContract, error) {")
	fmt.Fprintln(out, "\tswitch name {")
	for _, contract := range contracts {
		goType := contract.manual
		if contract.model != nil {
			goType = contract.model.name
		}
		fmt.Fprintf(out, "\tcase %q:\n", contract.name)
		fmt.Fprintln(out, "\t\t{")
		fmt.Fprintf(out, "\t\t\tvalue, err := %s(v, raw)\n", contract.builder)
		fmt.Fprintln(out, "\t\t\tif err != nil {")
		fmt.Fprintln(out, "\t\t\t\treturn nil, err")
		fmt.Fprintln(out, "\t\t\t}")
		fmt.Fprintln(out, "\t\t\treturn value, nil")
		fmt.Fprintln(out, "\t\t}")
		_ = goType
	}
	fmt.Fprintln(out, "\tdefault:")
	out.WriteString("\t\treturn nil, fmt.Errorf(\"platformcontract: no generated typed dispatch for %q\", name)\n")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
	for _, contract := range contracts {
		goType := contract.manual
		if contract.model != nil {
			goType = contract.model.name
		}
		fmt.Fprintf(out, "func (v *Validator) Decode%s(raw []byte) (%s, error) {\n", contract.name, goType)
		fmt.Fprintf(out, "\tvar zero %s\n", goType)
		fmt.Fprintln(out, "\tvalue, err := ParseStrictJSON(raw)")
		fmt.Fprintln(out, "\tif err != nil {")
		fmt.Fprintln(out, "\t\treturn zero, err")
		fmt.Fprintln(out, "\t}")
		fmt.Fprintf(out, "\tif err := v.validate(%q, value); err != nil {\n", contract.name)
		fmt.Fprintln(out, "\t\treturn zero, err")
		fmt.Fprintln(out, "\t}")
		fmt.Fprintf(out, "\treturn %s(v, value)\n", contract.builder)
		fmt.Fprintln(out, "}")
		fmt.Fprintln(out)
	}
}

func (g *generator) primaryEnumCount() int {
	count := 0
	for _, enum := range g.enums {
		// Branch-only enum types are suffixed Value by valueSpec. The frozen
		// primary set is independently pinned by schema traversal below.
		_ = enum
	}
	for _, doc := range g.documents {
		var walk func(map[string]any, bool)
		walk = func(node map[string]any, constrained bool) {
			if node == nil {
				return
			}
			if _, ok := node["enum"]; ok && !constrained {
				count++
			}
			for _, raw := range mapValue(node["properties"]) {
				child, _ := raw.(map[string]any)
				walk(child, constrained)
			}
			for _, raw := range mapValue(node["$defs"]) {
				child, _ := raw.(map[string]any)
				walk(child, constrained)
			}
			if child, _ := node["items"].(map[string]any); child != nil {
				walk(child, constrained)
			}
			for _, key := range []string{"additionalProperties", "propertyNames"} {
				if child, _ := node[key].(map[string]any); child != nil {
					walk(child, true)
				}
			}
			for _, key := range []string{"allOf", "oneOf", "anyOf"} {
				for _, raw := range arrayValue(node[key]) {
					child, _ := raw.(map[string]any)
					walk(child, true)
				}
			}
			for _, key := range []string{"if", "then", "else", "not", "contains"} {
				if child, _ := node[key].(map[string]any); child != nil {
					walk(child, true)
				}
			}
		}
		walk(doc.root, false)
	}
	return count
}

func (g *generator) fieldDispositions() (map[string]string, error) {
	result := map[string]string{}
	for _, doc := range g.documents {
		for _, name := range sortedMapKeys(doc.defs) {
			node, _ := doc.defs[name].(map[string]any)
			owner := g.typeNames[doc.key+"#/$defs/"+escapePointer(name)]
			g.collectDispositions(doc, node, doc.key+"#/$defs/"+escapePointer(name), owner, "", result)
		}
		owner := doc.rootName
		g.collectDispositions(doc, doc.root, doc.key+"#", owner, "", result)
	}
	return result, nil
}

func (g *generator) collectDispositions(
	doc *schemaDocument,
	node map[string]any,
	pointer string,
	owner string,
	union string,
	result map[string]string,
) {
	if node == nil {
		return
	}
	properties := mapValue(node["properties"])
	required := stringSet(node["required"])
	_ = required
	for _, jsonName := range sortedMapKeys(properties) {
		child, _ := properties[jsonName].(map[string]any)
		childPointer := pointer + "/properties/" + escapePointer(jsonName)
		switch {
		case child["writeOnly"] == true:
			result[childPointer] = "transport-only:" + owner + "." + goIdentifier(jsonName)
		case union != "":
			result[childPointer] = "union:" + union
		default:
			result[childPointer] = "field:" + owner + "." + goIdentifier(jsonName)
		}
		childOwner := owner + goIdentifier(jsonName)
		if model := g.modelsByRef[doc.key+strings.TrimPrefix(childPointer, doc.key)]; model != nil {
			childOwner = model.name
		} else if model := g.modelsByName[owner]; model != nil {
			for _, field := range model.fields {
				if field.jsonName != jsonName {
					continue
				}
				spec := field.spec
				if spec.slice {
					spec = spec.element
				}
				if spec.model != nil {
					childOwner = spec.model.name
				}
				break
			}
		} else if rawRef, _ := child["$ref"].(string); rawRef != "" {
			name := strings.TrimPrefix(rawRef, "#/$defs/")
			if generated := g.typeNames[doc.key+"#/$defs/"+name]; generated != "" {
				childOwner = generated
			}
		} else if child["type"] == "array" {
			if items, _ := child["items"].(map[string]any); items != nil {
				if rawRef, _ := items["$ref"].(string); rawRef != "" {
					name := strings.TrimPrefix(rawRef, "#/$defs/")
					if generated := g.typeNames[doc.key+"#/$defs/"+name]; generated != "" {
						childOwner = generated
					}
				}
			}
		}
		g.collectDispositions(doc, child, childPointer, childOwner, union, result)
	}
	for index, raw := range arrayValue(node["allOf"]) {
		child, _ := raw.(map[string]any)
		g.collectDispositions(doc, child, pointer+"/allOf/"+strconv.Itoa(index), owner, union, result)
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		for index, raw := range arrayValue(node[keyword]) {
			child, _ := raw.(map[string]any)
			unionPointer := pointer + "/" + keyword
			g.collectDispositions(doc, child, pointer+"/"+keyword+"/"+strconv.Itoa(index), owner, unionPointer, result)
		}
	}
	for _, keyword := range []string{"if", "then", "else", "contains", "additionalProperties"} {
		child, _ := node[keyword].(map[string]any)
		if child != nil {
			g.collectDispositions(doc, child, pointer+"/"+keyword, owner, union, result)
		}
	}
	if child, _ := node["items"].(map[string]any); child != nil {
		g.collectDispositions(doc, child, pointer+"/items", owner, union, result)
	}
}

func sortedStringKeys(value map[string]string) []string {
	keys := make([]string, 0, len(value))
	for key := range value {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
