package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

func (g *generator) renderManifests() ([]byte, error) {
	roots, err := g.prepareManifestModels()
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/gentypes; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Frozen input digest: %s\n", inputDigest(g.inputs))
	fmt.Fprintln(&out, "package platformcontract")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, `import "fmt"`)
	fmt.Fprintln(&out)

	models := append([]*manifestObjectModel(nil), g.manifestObjs...)
	sort.Slice(models, func(i, j int) bool { return models[i].name < models[j].name })
	rootNames := map[string]string{}
	for _, root := range roots {
		rootNames[root.model.name] = root.file.key
	}
	for _, model := range models {
		emitManifestObject(&out, model, rootNames[model.name])
	}
	unions := append([]*manifestUnionModel(nil), g.manifestUnions...)
	sort.Slice(unions, func(i, j int) bool { return unions[i].name < unions[j].name })
	for _, union := range unions {
		emitManifestUnion(&out, union)
	}

	fmt.Fprintf(&out, "const GeneratedManifestCount = %d\n", len(roots))
	structuralFields := 0
	for _, model := range models {
		structuralFields += len(model.fields)
	}
	fmt.Fprintf(&out, "const GeneratedManifestStructuralFieldCount = %d\n", structuralFields)
	dispositions, err := g.manifestFieldDispositions(roots)
	if err != nil {
		return nil, err
	}
	if len(dispositions) != 596 {
		return nil, fmt.Errorf(
			"gentypes: generated manifest property dispositions=%d, want 596",
			len(dispositions),
		)
	}
	fmt.Fprintf(&out, "const GeneratedManifestPropertyCount = %d\n", len(dispositions))
	fmt.Fprintf(
		&out,
		"const GeneratedManifestFieldDispositionSHA256 = %q\n",
		fieldDispositionDigest(dispositions),
	)
	fmt.Fprintln(&out, "var generatedManifestFieldDispositions = map[string]string{")
	for _, pointer := range sortedStringKeys(dispositions) {
		fmt.Fprintf(&out, "\t%q: %q,\n", pointer, dispositions[pointer])
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var generatedManifestFieldAccessors = map[string]any{")
	for _, pointer := range sortedStringKeys(dispositions) {
		disposition := dispositions[pointer]
		target, ok := strings.CutPrefix(disposition, "field:")
		if !ok {
			continue
		}
		separator := strings.LastIndex(target, ".")
		if separator <= 0 || separator == len(target)-1 {
			return nil, fmt.Errorf(
				"gentypes: malformed manifest field disposition %q for %s",
				disposition,
				pointer,
			)
		}
		fmt.Fprintf(
			&out,
			"\t%q: %s.%s,\n",
			pointer,
			target[:separator],
			target[separator+1:],
		)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var generatedManifestUnionTags = map[string]any{")
	for _, pointer := range sortedStringKeys(dispositions) {
		disposition := dispositions[pointer]
		target, ok := strings.CutPrefix(disposition, "union:")
		if !ok {
			continue
		}
		fmt.Fprintf(&out, "\t%q: %s.Kind,\n", pointer, target)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "func GeneratedManifestFieldDispositions() map[string]string {")
	fmt.Fprintln(&out, "\tresult := make(map[string]string, len(generatedManifestFieldDispositions))")
	fmt.Fprintln(&out, "\tfor pointer, disposition := range generatedManifestFieldDispositions {")
	fmt.Fprintln(&out, "\t\tresult[pointer] = disposition")
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "\treturn result")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "func buildGeneratedManifest(name string, raw map[string]any) (FrozenManifest, error) {")
	fmt.Fprintln(&out, "\tswitch name {")
	sort.Slice(roots, func(i, j int) bool { return roots[i].file.key < roots[j].file.key })
	for _, root := range roots {
		fmt.Fprintf(&out, "\tcase %q:\n", root.file.key)
		fmt.Fprintln(&out, "\t\t{")
		fmt.Fprintf(&out, "\t\t\tvalue, err := build%s(raw)\n", root.model.name)
		fmt.Fprintln(&out, "\t\t\tif err != nil {")
		fmt.Fprintln(&out, "\t\t\t\treturn nil, err")
		fmt.Fprintln(&out, "\t\t\t}")
		fmt.Fprintln(&out, "\t\t\treturn value, nil")
		fmt.Fprintln(&out, "\t\t}")
	}
	fmt.Fprintln(&out, "\tdefault:")
	out.WriteString("\t\treturn nil, fmt.Errorf(\"platformcontract: no generated manifest type for %q\", name)\n")
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "}")
	return out.Bytes(), nil
}

func emitManifestUnion(out *bytes.Buffer, union *manifestUnionModel) {
	kindName := union.name + "Kind"
	fmt.Fprintf(out, "type %s uint8\n", kindName)
	fmt.Fprintln(out, "const (")
	fmt.Fprintf(out, "\t%sInvalid %s = iota\n", kindName, kindName)
	for _, variant := range union.variants {
		fmt.Fprintf(out, "\t%s%s\n", kindName, variant.name)
	}
	fmt.Fprintln(out, ")")
	fmt.Fprintf(out, "type %s struct {\n", union.name)
	fmt.Fprintf(out, "\tkind %s\n", kindName)
	for _, variant := range union.variants {
		fmt.Fprintf(
			out,
			"\t%s optionalValue[%s]\n",
			variant.private,
			variant.spec.goType,
		)
	}
	fmt.Fprintln(out, "}")
	fmt.Fprintf(
		out,
		"func (value %s) Kind() %s { return value.kind }\n",
		union.name,
		kindName,
	)
	for _, variant := range union.variants {
		fmt.Fprintf(
			out,
			"func (value %s) %s() (%s, bool) {\n",
			union.name,
			variant.name,
			variant.spec.goType,
		)
		fmt.Fprintf(out, "\tif !value.%s.set {\n", variant.private)
		fmt.Fprintf(out, "\t\tvar zero %s\n", variant.spec.goType)
		fmt.Fprintln(out, "\t\treturn zero, false")
		fmt.Fprintln(out, "\t}")
		fmt.Fprintf(out, "\treturn value.%s.value, true\n", variant.private)
		fmt.Fprintln(out, "}")
	}
	fmt.Fprintf(out, "func build%s(raw any) (%s, error) {\n", union.name, union.name)
	fmt.Fprintf(out, "\tobject, err := requireObject(raw, %q)\n", union.name)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", union.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\tbranch := -1")
	for index, variant := range union.variants {
		object := variant.value.(map[string]any)
		keys := sortedMapKeys(object)
		fmt.Fprintf(out, "\tif len(object) == %d {\n", len(keys))
		for keyIndex, key := range keys {
			fmt.Fprintf(
				out,
				"\t\t_, field%dPresent := object[%q]\n",
				keyIndex,
				key,
			)
		}
		fmt.Fprint(out, "\t\tif ")
		for keyIndex := range keys {
			if keyIndex > 0 {
				fmt.Fprint(out, " && ")
			}
			fmt.Fprintf(out, "field%dPresent", keyIndex)
		}
		fmt.Fprintln(out, " {")
		fmt.Fprintf(out, "\t\t\tbranch = %d\n", index)
		fmt.Fprintln(out, "\t\t}")
		fmt.Fprintln(out, "\t}")
	}
	fmt.Fprintln(out, "\tif branch < 0 {")
	fmt.Fprintf(
		out,
		"\t\treturn %s{}, fmt.Errorf(\"platformcontract: generated manifest union %s matched no exact object shape\")\n",
		union.name,
		union.name,
	)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\tvar result %s\n", union.name)
	fmt.Fprintf(out, "\tresult.kind = %s(branch + 1)\n", kindName)
	fmt.Fprintln(out, "\tswitch branch {")
	for index, variant := range union.variants {
		fmt.Fprintf(out, "\tcase %d:\n", index)
		emitManifestBuild(out, variant.spec, "raw", "converted", "\t\t")
		fmt.Fprintf(
			out,
			"\t\tresult.%s = presentValue(converted)\n",
			variant.private,
		)
	}
	fmt.Fprintln(out, "\tdefault:")
	fmt.Fprintf(
		out,
		"\t\treturn %s{}, fmt.Errorf(\"platformcontract: generated manifest union branch %%d is invalid\", branch)\n",
		union.name,
	)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "\treturn result, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

type manifestRoot struct {
	file  *manifestFile
	model *manifestObjectModel
}

func (g *generator) prepareManifestModels() ([]manifestRoot, error) {
	var roots []manifestRoot
	for _, file := range g.manifests {
		spec, err := g.manifestSpec(file.value, file.goName, "manifest:"+file.filename+"#")
		if err != nil {
			return nil, err
		}
		if spec.object == nil {
			return nil, fmt.Errorf("gentypes: manifest %s is not an object", file.filename)
		}
		roots = append(roots, manifestRoot{file: file, model: spec.object})
	}
	return roots, nil
}

func (g *generator) manifestSpec(value any, suggested, identity string) (*manifestValueSpec, error) {
	switch item := value.(type) {
	case string:
		return &manifestValueSpec{goType: "string", kind: "string"}, nil
	case bool:
		return &manifestValueSpec{goType: "bool", kind: "boolean"}, nil
	case json.Number:
		return &manifestValueSpec{goType: "JSONNumber", kind: "number"}, nil
	case nil:
		return &manifestValueSpec{goType: "ManifestValue", kind: "value"}, nil
	case []any:
		if len(item) == 0 {
			return &manifestValueSpec{
				goType:  "[]ManifestValue",
				kind:    "slice",
				element: &manifestValueSpec{goType: "ManifestValue", kind: "value"},
			}, nil
		}
		shape := manifestShape(item[0])
		homogeneous := true
		for _, child := range item[1:] {
			if manifestShape(child) != shape {
				homogeneous = false
				break
			}
		}
		if !homogeneous {
			return g.manifestUnionSliceSpec(item, suggested, identity)
		}
		element, err := g.manifestSpec(item[0], suggested+"Item", identity+"/*")
		if err != nil {
			return nil, err
		}
		return &manifestValueSpec{
			goType:  "[]" + element.goType,
			kind:    "slice",
			element: element,
		}, nil
	case map[string]any:
		if priorName := g.manifestNames[identity]; priorName != "" {
			for _, model := range g.manifestObjs {
				if model.name == priorName {
					return &manifestValueSpec{goType: model.name, kind: "object", object: model}, nil
				}
			}
		}
		name := g.uniqueTypeName(suggested, identity)
		model := &manifestObjectModel{name: name}
		g.manifestNames[identity] = name
		g.manifestObjs = append(g.manifestObjs, model)
		usedFields := map[string]string{}
		for _, jsonName := range sortedMapKeys(item) {
			goName := goIdentifier(jsonName)
			if prior := usedFields[goName]; prior != "" && prior != jsonName {
				goName += shortHash(jsonName)
			}
			usedFields[goName] = jsonName
			child, err := g.manifestSpec(
				item[jsonName],
				name+goName,
				identity+"/"+escapePointer(jsonName),
			)
			if err != nil {
				return nil, err
			}
			model.fields = append(model.fields, &manifestFieldModel{
				jsonName: jsonName,
				goName:   goName,
				private:  privateIdentifier(goName),
				value:    item[jsonName],
				spec:     child,
			})
		}
		return &manifestValueSpec{goType: name, kind: "object", object: model}, nil
	default:
		return nil, fmt.Errorf("gentypes: unsupported manifest value %T", value)
	}
}

func (g *generator) manifestUnionSliceSpec(
	values []any,
	suggested string,
	identity string,
) (*manifestValueSpec, error) {
	byShape := make(map[string]any)
	for _, value := range values {
		shape := manifestShape(value)
		if _, exists := byShape[shape]; !exists {
			byShape[shape] = value
		}
	}
	shapes := make([]string, 0, len(byShape))
	for shape := range byShape {
		shapes = append(shapes, shape)
	}
	sort.Strings(shapes)

	unionName := g.uniqueTypeName(suggested+"Value", identity+"/union")
	union := &manifestUnionModel{name: unionName}
	directObjectKeys := make(map[string]string)
	for index, shape := range shapes {
		value := byShape[shape]
		object, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf(
				"gentypes: heterogeneous manifest array %s has non-object shape %s",
				identity,
				shape,
			)
		}
		if len(object) == 0 {
			return nil, fmt.Errorf(
				"gentypes: heterogeneous manifest array %s has an empty-object "+
					"variant with no deterministic discriminator",
				identity,
			)
		}
		keySignature := strings.Join(sortedMapKeys(object), "\x00")
		if prior := directObjectKeys[keySignature]; prior != "" {
			return nil, fmt.Errorf(
				"gentypes: heterogeneous manifest array %s has shapes that cannot be "+
					"distinguished by exact object fields: %s and %s",
				identity,
				prior,
				shape,
			)
		}
		directObjectKeys[keySignature] = shape

		name := "Variant" + strconv.Itoa(index+1)
		spec, err := g.manifestSpec(
			value,
			unionName+name,
			identity+"/union/"+strconv.Itoa(index),
		)
		if err != nil {
			return nil, err
		}
		union.variants = append(union.variants, &manifestUnionVariant{
			name:    name,
			private: privateIdentifier(name),
			shape:   shape,
			value:   value,
			spec:    spec,
		})
	}
	g.manifestUnions = append(g.manifestUnions, union)
	element := &manifestValueSpec{
		goType: union.name,
		kind:   "union",
		union:  union,
	}
	return &manifestValueSpec{
		goType:  "[]" + union.name,
		kind:    "slice",
		element: element,
	}, nil
}

func manifestShape(value any) string {
	switch item := value.(type) {
	case nil:
		return "null"
	case string:
		return "string"
	case bool:
		return "boolean"
	case json.Number:
		return "number"
	case []any:
		shapes := map[string]bool{}
		for _, child := range item {
			shapes[manifestShape(child)] = true
		}
		keys := make([]string, 0, len(shapes))
		for key := range shapes {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		return "array[" + strings.Join(keys, "|") + "]"
	case map[string]any:
		var parts []string
		for _, key := range sortedMapKeys(item) {
			parts = append(parts, key+":"+manifestShape(item[key]))
		}
		return "object{" + strings.Join(parts, ",") + "}"
	default:
		return fmt.Sprintf("%T", value)
	}
}

func emitManifestObject(out *bytes.Buffer, model *manifestObjectModel, manifestName string) {
	fmt.Fprintf(out, "type %s struct {\n", model.name)
	for _, field := range model.fields {
		fmt.Fprintf(out, "\t%s %s\n", field.private, field.spec.goType)
	}
	fmt.Fprintln(out, "}")
	if manifestName != "" {
		fmt.Fprintf(out, "func (%s) ManifestName() string { return %q }\n", model.name, manifestName)
		fmt.Fprintf(out, "func (%s) sealedFrozenManifest() {}\n", model.name)
	}
	for _, field := range model.fields {
		fmt.Fprintf(out, "func (value %s) %s() %s {\n", model.name, field.goName, field.spec.goType)
		if field.spec.kind == "slice" {
			fmt.Fprintf(out, "\treturn append([]%s(nil), value.%s...)\n", field.spec.element.goType, field.private)
		} else {
			fmt.Fprintf(out, "\treturn value.%s\n", field.private)
		}
		fmt.Fprintln(out, "}")
	}
	fmt.Fprintf(out, "func build%s(raw any) (%s, error) {\n", model.name, model.name)
	fmt.Fprintf(out, "\tobject, err := requireObject(raw, %q)\n", model.name)
	fmt.Fprintln(out, "\tif err != nil {")
	fmt.Fprintf(out, "\t\treturn %s{}, err\n", model.name)
	fmt.Fprintln(out, "\t}")
	fmt.Fprintf(out, "\tvar result %s\n", model.name)
	for _, field := range model.fields {
		emitManifestBuild(out, field.spec, "object["+strconv.Quote(field.jsonName)+"]", "converted"+field.goName, "\t")
		fmt.Fprintf(out, "\tresult.%s = converted%s\n", field.private, field.goName)
	}
	fmt.Fprintln(out, "\treturn result, nil")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func emitManifestBuild(out *bytes.Buffer, spec *manifestValueSpec, source, variable, indent string) {
	switch spec.kind {
	case "string":
		fmt.Fprintf(out, "%s%s, err := buildManifestString(%s)\n", indent, variable, source)
	case "boolean":
		fmt.Fprintf(out, "%s%s, err := buildManifestBoolean(%s)\n", indent, variable, source)
	case "number":
		fmt.Fprintf(out, "%s%s, err := buildManifestNumber(%s)\n", indent, variable, source)
	case "value":
		fmt.Fprintf(out, "%s%s, err := buildManifestValue(%s)\n", indent, variable, source)
	case "object":
		fmt.Fprintf(out, "%s%s, err := build%s(%s)\n", indent, variable, spec.object.name, source)
	case "slice":
		builder := manifestBuilderExpression(spec.element)
		fmt.Fprintf(out, "%s%s, err := buildManifestSlice(%s, %q, %s)\n", indent, variable, source, variable, builder)
	default:
		panic("unknown manifest spec kind " + spec.kind)
	}
	fmt.Fprintf(out, "%sif err != nil {\n", indent)
	fmt.Fprintf(out, "%s\treturn result, err\n", indent)
	fmt.Fprintf(out, "%s}\n", indent)
}

func manifestBuilderExpression(spec *manifestValueSpec) string {
	switch spec.kind {
	case "string":
		return "buildManifestString"
	case "boolean":
		return "buildManifestBoolean"
	case "number":
		return "buildManifestNumber"
	case "value":
		return "buildManifestValue"
	case "object":
		return "build" + spec.object.name
	case "union":
		return "build" + spec.union.name
	case "slice":
		return fmt.Sprintf(
			"func(raw any) (%s, error) { return buildManifestSlice(raw, %q, %s) }",
			spec.goType,
			"nested manifest array",
			manifestBuilderExpression(spec.element),
		)
	default:
		panic("unknown manifest builder kind " + spec.kind)
	}
}

func (g *generator) manifestFieldDispositions(
	roots []manifestRoot,
) (map[string]string, error) {
	result := make(map[string]string)
	for _, root := range roots {
		if err := collectManifestFieldDispositions(
			root.file.value,
			&manifestValueSpec{
				goType: root.model.name,
				kind:   "object",
				object: root.model,
			},
			root.file.filename+"#",
			"",
			result,
		); err != nil {
			return nil, err
		}
	}
	return result, nil
}

func collectManifestFieldDispositions(
	value any,
	spec *manifestValueSpec,
	pointer string,
	union string,
	result map[string]string,
) error {
	switch item := value.(type) {
	case map[string]any:
		if spec == nil || spec.kind != "object" || spec.object == nil {
			return fmt.Errorf(
				"gentypes: manifest object %s has generated spec %v",
				pointer,
				spec,
			)
		}
		fields := make(map[string]*manifestFieldModel, len(spec.object.fields))
		for _, field := range spec.object.fields {
			fields[field.jsonName] = field
		}
		for _, jsonName := range sortedMapKeys(item) {
			field := fields[jsonName]
			if field == nil {
				return fmt.Errorf(
					"gentypes: manifest object %s has no generated field for %s",
					pointer,
					jsonName,
				)
			}
			childPointer := pointer + "/" + escapePointer(jsonName)
			disposition := "field:" + spec.object.name + "." + field.goName
			if union != "" {
				disposition = "union:" + union
			}
			if prior := result[childPointer]; prior != "" && prior != disposition {
				return fmt.Errorf(
					"gentypes: manifest property %s has dispositions %s and %s",
					childPointer,
					prior,
					disposition,
				)
			}
			result[childPointer] = disposition
			if err := collectManifestFieldDispositions(
				item[jsonName],
				field.spec,
				childPointer,
				union,
				result,
			); err != nil {
				return err
			}
		}
	case []any:
		if len(item) == 0 {
			return nil
		}
		if spec == nil || spec.kind != "slice" || spec.element == nil {
			return fmt.Errorf(
				"gentypes: manifest array %s has generated spec %v",
				pointer,
				spec,
			)
		}
		childPointer := pointer + "/*"
		if spec.element.kind == "union" {
			for _, variant := range spec.element.union.variants {
				if err := collectManifestFieldDispositions(
					variant.value,
					variant.spec,
					childPointer,
					spec.element.union.name,
					result,
				); err != nil {
					return err
				}
			}
			return nil
		}
		return collectManifestFieldDispositions(
			item[0],
			spec.element,
			childPointer,
			union,
			result,
		)
	}
	return nil
}
