// Command freeze copies the accepted, read-only platform contract inputs into
// a generated Go source file.  It deliberately has no network behaviour.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
)

func main() {
	check := flag.Bool("check", false, "verify generated output is current")
	rootFlag := flag.String("root", "", "override contracts/platform input directory")
	outputFlag := flag.String("output", "", "override generated output file")
	flag.Parse()
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		panic("freeze: cannot locate generator source")
	}
	sourceDir := filepath.Dir(sourceFile)
	root := *rootFlag
	if root == "" {
		root = filepath.Clean(filepath.Join(sourceDir, "../../../../../contracts/platform"))
	}
	output := *outputFlag
	if output == "" {
		output = filepath.Clean(filepath.Join(sourceDir, "../../frozen_contracts_gen.go"))
	}
	files := []string{
		"schemas/platform-v1.schema.json", "schemas/remediation-proposal-v1.schema.json", "schemas/recovery-evidence-v1.schema.json",
		"manifests/failure-injection-v1.json", "manifests/http-rate-limits-v1.json", "manifests/migration-policy-v1.json", "manifests/nats-permissions-v1.json", "manifests/phase0-file-manifest-v1.json", "manifests/recovery-policy-v1.json", "manifests/security-values-v1.json", "manifests/state-machines-v1.json", "manifests/transaction-boundaries-v1.json", "manifests/websocket-protocol-v1.json",
		"../fixtures/platform/executable-security-scenarios-v1.json", "../fixtures/platform/golden-vectors-v1.json", "../fixtures/platform/invalid-schema-cases-v1.json", "../fixtures/platform/linkage-chains-v1.json", "../fixtures/platform/semantic-scenarios-v1.json", "../fixtures/platform/valid-schema-cases-v1.json",
	}
	sort.Strings(files)
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out, "package platformcontract")
	fmt.Fprintln(&out, "")
	fmt.Fprintln(&out, "var frozenContractBase64 = map[string]string{")
	for _, name := range files {
		body, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&out, "\t%s: %s,\n", strconv.Quote(name), strconv.Quote(base64.StdEncoding.EncodeToString(body)))
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "var frozenContractSHA256 = map[string]string{")
	for _, name := range files {
		body, _ := os.ReadFile(filepath.Join(root, name))
		sum := sha256.Sum256(body)
		fmt.Fprintf(&out, "\t%s: %q,\n", strconv.Quote(name), fmt.Sprintf("%x", sum))
	}
	fmt.Fprintln(&out, "}")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if *check {
		current, err := os.ReadFile(output)
		if err != nil || !bytes.Equal(current, formatted) {
			panic("frozen_contracts_gen.go is stale; run go generate or go run ./cmd/freeze")
		}
		return
	}
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		panic(err)
	}
}
